# Generated by Django 5.1.4 on 2024-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowing_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
