# Generated by Django 5.1.4 on 2024-12-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_borrowing_price_borrowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowhistory',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
